# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 20:24
from __future__ import unicode_literals

import datasubmission.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date submitted')),
                ('submitted_filename', models.CharField(max_length=256)),
                ('stored_filename', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionTokenBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(default=datasubmission.models.default_new_id_code, max_length=32, unique=True, verbose_name='ID Code')),
                ('issued_to', models.CharField(max_length=128, verbose_name='Issued To')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Issued At')),
                ('used', models.BooleanField(default=False, verbose_name='Used')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='token_body',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datasubmission.SubmissionTokenBody'),
        ),
    ]
