# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasubmission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissiontokenbody',
            name='used',
        ),
        migrations.AlterField(
            model_name='submission',
            name='token_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasubmission.SubmissionTokenBody'),
        ),
    ]
